version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: modsutd
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modsutd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Backend API
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://modsutd:password@postgres:5432/modsutd?schema=public"
      JWT_SECRET: "your-super-secret-jwt-key-here"
      PORT: 4000
      NODE_ENV: development
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      FRONTEND_URL: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  # Frontend
  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

  # Database management tool (optional)
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge